### PR TITLE
Kill false conflict alarm

### PR DESCRIPTION
**Pull request by cstamas**
Also my pet peeve, do tell something, anything about work done.

Example output (mvnd):
```
[INFO] --- provisio:1.0.27-SNAPSHOT:provision (maven-distro) @ mvnd-dist ---
[INFO] Provisioning done in 1 sec (total of 132 files processed, 2 archives produced)
```

### CODE REVIEW

**Comment by cstamas** [comment]
@gnodet

**Review by gnodet — APPROVED** [review]
LGTM

**Review by wendigo — APPROVED** [review]

**Comment by cstamas** [comment]
@wendigo I tested this on mvnd and is ok, can you test this on Trino? (dont forget to add property):
```
        <provisio.fallbackTargetFileNameMode>GA</provisio.fallbackTargetFileNameMode>

```

**Comment by cstamas** [comment]
Trino build: with GA fallback, now provisio properly fails due real conflict:
```
[ERROR] Failed to execute goal ca.vanzyl.provisio.maven.plugins:provisio-maven-plugin:1.0.27-SNAPSHOT:provision (default-provision) on project trino-accumulo: Error provisioning assembly.: Conflict: artifact io.opentelemetry.semconv:opentelemetry-semconv:jar:1.27.0-alpha would overwrite existing file: opentelemetry-semconv-1.27.0-alpha.jar -> [Help 1]
```
So this is OK, now let's see with GA

**Comment by cstamas** [comment]
Before last 2 commit: GA fallback failed, as hardlinks (in trino server targz) were detected as "conflicts".

After last 2 commit:
```
[INFO] --- provisio:1.0.27-SNAPSHOT:provision (unpack) @ trino-server-rpm ---
[INFO] Loaded 2 groupId for remote repository confluent
[INFO] Provisioning done in 2 sec (total of 6202 files processed, 0 archives produced)
```

**Pull request merged**
